type:build:

  - "main/*"

  - ".github/**/*"

  - ".coveralls.yml"

  - ".gitignore"

  - "ecs.yml"

  - "phpcs.xml"

  - "front/**/*"

dependencies:

  - "front/package.json"

  - "front/package-lock.json"

theme:docs:

  - "README.md"

  - "LICENSE"

  - "CONTRIBUTING.md"

  - "CODE_OF_CONDUCT.md"
